### ISSUE TITLE
XML file needs to be external to the code

### ISSUE THREAD

**Issue by fartbagxp** [RaxaStudios/kfbot#1]
The current architecture requires the XML file to be within the code.

That is `not acceptable` .

The user will have the XML file in the `local folder` of the jar.

**Comment by fartbagxp** [comment]
There's a part that reads the XML file, something like `File file = new File("resources/someFile.xml")`
Since the property file should be external to the jar, the path should really be File("./someFile.xml")

Here's a stackoverflow article on what that means:
http://stackoverflow.com/questions/8775303/read-properties-file-outside-jar-file

**Comment by RaxaStudios** [comment]
See "Updated XML usage" commit
