### ISSUE TITLE
Commands checking for names are currently case-sensitive

### ISSUE THREAD

**Issue by fartbagxp** [RaxaStudios/kfbot#13]
Scenario: User specified in the XML file can be specified in any form, such as "Fartbagxp" or "fartbagxp".
The username may not match the Twitch name, because it may be capitalized or lowercase.
The bot is currently restrictive to case-sensitive matching of username.

This will allow the usage of "FartbagXp", "faRtbagXp", and still allow authorization to work.

This is currently both a bug and an enhancement.

**Comment by RaxaStudios** [comment]
Fixed with commit "Issues #13"
