### ISSUE TITLE
Expected Youtube description is wrong

### ISSUE THREAD

**Issue by fartbagxp** [RaxaStudios/kfbot#3]
The youtube handler has issues currently.

`Input to the youtube handler`: https://www.youtube.com/watch?v=SwYN7mTi6HM
`Currently output`: d=GCrWV-qqFoOd8gTQ-oXYDQ
`Expected output`: Van Halen - Jump

**Comment by fartbagxp** [comment]
We should register for an google API key instead and use this API.
The API allows for a few million calls a day, before you have to pay for it.
https://developers.google.com/youtube/v3/docs/videos/list

To get the correct response back, here's an example:
http://stackoverflow.com/questions/30084140/youtube-video-title-with-api-v3-without-api-key

**Comment by RaxaStudios** [comment]
Updated using google API XML : <youtubeAPI> for key and <youtubeTitle> for API call link to grab title
